apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: taskapp
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "5"
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      restartPolicy: OnFailure
      containers:                           
        - name: migration
          image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
          command: ["python", "-m", "flask", "db", "upgrade"]
          envFrom:
            - configMapRef:
                name: taskapp-config
            - secretRef:
                name: taskapp-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL