apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  FLASK_ENV: "production"
  FLASK_APP: "app.py"
  DB_HOST: "postgres.taskapp.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "taskapp"
  DB_USER: "postgres"
  REACT_APP_API_URL: "https://api.sopuruchi.duckdns.org"