apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RealNald/capstone-phoenix.git
    targetRevision: main
    path: manifests/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RealNald/capstone-phoenix.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true